### PR TITLE
Allowing multiple syscalls

### PR DESCRIPTION
**Pull request by igormcoelho**

### CODE REVIEW

**Comment by lightszero** [comment]
why multiple syscalls？i dont think this can work fine.

**Comment by cristcardosop** [comment]
@lightszero it works fine, it's amazing.. Please see this https://github.com/neo-project/neo-devpack-dotnet/pull/36
(BTW, I'm using my wife username.. It's igormcoelho :))

**Comment by lightszero** [comment]
> @lightszero it works fine, it's amazing.. Please see this [neo-project/neo-devpack-dotnet#36](https://github.com/neo-project/neo-devpack-dotnet/pull/36)
> (BTW, I'm using my wife username.. It's igormcoelho :))

see it, this is only can be work when first syscall is no need for params.

so,i think we need discuss that solution more.

**Comment by cristcardosop** [comment]
You got a point. It would be nice to inline everything.

**Pull request closed without merging**
